services:
  postgres:
    container_name: nest-clean-arch-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest-clean-arch
    volumes:
      - ./data/pg:/data/postgres
  
  cache:
    container_name: nest-clean-arch-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data